# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cpf_cnpj',
            new_name='cpf',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
    ]
