# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20170530_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productanswer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
