# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_userprofile_remote_receiver_id'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='portal.Product'),
        ),
    ]
