# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Packing', 'Packing'), ('Posted', 'Posted'), ('Delivered', 'Delivered')], default='Received', max_length=20),
        ),
    ]
